org: danvk
app: catskills-hike-planner
service: catskills-hike-planner
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: python3.10
  timeout: 28
  memorySize: 2048  # optional, in MB, default is 1024
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["CacheDynamoDBTable", "Arn" ] }
  environment:
    CACHE_TABLE: ${self:custom.tableName}
    GIT_SHA: ${param:git_sha}

package:
  # individually: true
  individually: false
  excludeDevDependencies: true
  exclude:
    - .git/**
    - .vscode/**
    - node_modules/**

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  find-hikes:
    handler: handler.find_hikes
    events:
      - httpApi:
          path: /find-hikes
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
  tableName: 'cache-table-${self:provider.stage}'

resources:
  Resources:
    CacheDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: gitShaRequestKey
            AttributeType: S
        KeySchema:
          -
            AttributeName: gitShaRequestKey
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
